### ISSUE TITLE
Using this library in a modular Java project

### ISSUE THREAD

**Issue by fstonedahl** [michael-ameri/gemini-api#2]
I was excited to find your Java API for Gemini, but the problem is we'd like to use it in a **modular** Java project, and currently won't work, because:

gemini.api.1beta.0.2.3: Invalid module name: '1beta' is not a Java identifier

This seems to be the same problem described here: https://stackoverflow.com/questions/46683561/how-to-resolve-a-maven-dependency-with-a-name-that-is-not-compliant-with-the-jav

I _believe_ you could easily fix this on your end by including another manifest entry into your build:

```
<manifestEntries>
   <Automatic-Module-Name>**your.module.name.here**</Automatic-Module-Name>
</manifestEntries>

```
as described here:https://stackoverflow.com/questions/46501388/unable-to-derive-module-descriptor-for-auto-generated-module-names-in-java-9

Any chance you could do that really quick, and roll out another release so I can test it?

The only workaround I see on my end is to manually re-jar your jars with this change myself, but then I can't use Maven or pull down newer versions, etc.

**Comment by michael-ameri** [comment]
@fstonedahl please try the newest version 1beta.0.2.4
I've added Automatic-Module-Name to the manifest

**Comment by fstonedahl** [comment]
Thanks for the quick response, that fixed the issue!
